apiVersion: batch/v1
kind: CronJob
metadata:
  name: client
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0  # 작업 종료 후 바로 삭제
      backoffLimit: 0   # 재시도 않음
      template:
        spec:
          containers:
          - name: client
            image: abtest-client
            resources:
              requests:
                memory: "6Gi"
                cpu: "1000m"
              limits:
                memory: "6Gi"
                cpu: "1000m"
          restartPolicy: Never
