apiVersion: batch/v1
kind: CronJob
metadata:
  name: client
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0  # 작업 종료 후 바로 삭제
      template:
        spec:
          containers:
          - name: client
            image: client
          restartPolicy: Never
