apiVersion: v1
kind: PersistentVolume
metadata:
  name: abtest-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abtest-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: manual
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: client
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0  # 작업 종료 후 바로 삭제
      backoffLimit: 0   # 재시도 않음
      template:
        spec:
          containers:
          - name: client
            image: abtest-client
            resources:
              requests:
                memory: "6Gi"
                cpu: "1000m"
              limits:
                memory: "6Gi"
                cpu: "1000m"
            volumeMounts:
            - name: abtest-vol
              mountPath: /data
          volumes:
          - name: abtest-vol
            persistentVolumeClaim:
              claimName: abtest-pvc
          restartPolicy: Never
