apiVersion: apps/v1
kind: Deployment
metadata:
  name: server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: abtest-server
        ports:
        - containerPort: 5000
        env:
        - name: ABTEST_APP
          valueFrom:
            secretKeyRef:
              name: abtest
              key: app
        - name: ABTEST_TOKEN
          valueFrom:
            secretKeyRef:
              name: abtest
              key: token
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5  
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
  - port: 80
    targetPort: 5000
